import type { LucideProps } from 'lucide-react-native';
import {
  Apple,
  Asterisk,
  Atom,
  Beef,
  Bell,
  Bike,
  Bone,
  Bookmark,
  CalendarDays,
  Camera,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Check,
  CircleDot,
  CircleHelp,
  Clock3,
  Contrast,
  Crown,
  Droplet,
  Droplets,
  Dumbbell,
  Ellipsis,
  FileText,
  Fish,
  Flame,
  Footprints,
  GlassWater,
  Globe,
  Hammer,
  Heart,
  Images,
  Info,
  Keyboard,
  Leaf,
  Mars,
  Minus,
  MoonStar,
  Navigation,
  Pencil,
  Plus,
  Scale,
  ScanBarcode,
  SendHorizontal,
  Settings2,
  SlidersHorizontal,
  Sparkles,
  SquareStack,
  Star,
  Target,
  Trash2,
  Trophy,
  Users,
  Utensils,
  Venus,
  Zap,
  Wheat,
  X,
} from 'lucide-react-native';

import { useColors } from '@/hooks/use-colors';

const icons = {
  apple: Apple,
  asterisk: Asterisk,
  beef: Beef,
  bell: Bell,
  bike: Bike,
  bookmark: Bookmark,
  calendar: CalendarDays,
  camera: Camera,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circleDot: CircleDot,
  circleHelp: CircleHelp,
  clock: Clock3,
  contrast: Contrast,
  crown: Crown,
  droplet: Droplet,
  droplets: Droplets,
  dumbbell: Dumbbell,
  ellipsis: Ellipsis,
  fileText: FileText,
  fish: Fish,
  flame: Flame,
  footprints: Footprints,
  glassWater: GlassWater,
  globe: Globe,
  heart: Heart,
  images: Images,
  info: Info,
  keyboard: Keyboard,
  leaf: Leaf,
  mars: Mars,
  minus: Minus,
  moonStar: MoonStar,
  navigation: Navigation,
  pencil: Pencil,
  plus: Plus,
  scale: Scale,
  scanBarcode: ScanBarcode,
  send: SendHorizontal,
  settings: Settings2,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  squareStack: SquareStack,
  star: Star,
  target: Target,
  trash: Trash2,
  trophy: Trophy,
  users: Users,
  utensils: Utensils,
  venus: Venus,
  zap: Zap,
  wheat: Wheat,
  x: X,
  // Sugar/sodium get their own names so iOS can show cube/salt without
  // changing 'sets' (squareStack) or 'athlete' (asterisk). Android keeps the
  // same glyphs it already had.
  sugar: SquareStack,
  sodium: Asterisk,
  // Micronutrient categories — ready for when tracking grows past
  // sugar/fiber/sodium. Reuse a few base glyphs (energy = Zap, sparkle = AI/vit).
  vitamins: Sparkles,
  antioxidants: Sparkles,
  minerals: Atom,
  electrolytes: Zap,
  potassium: Zap,
  magnesium: Zap,
  iron: Hammer,
  calcium: Bone,
  omega3: Droplet,
} as const;

export type AppIconName = keyof typeof icons;

interface AppIconProps extends Omit<LucideProps, 'color'> {
  name: AppIconName;
  color?: string;
}

export function AppIcon({
  name,
  color,
  size = 18,
  strokeWidth = 2.1,
  ...rest
}: AppIconProps) {
  const colors = useColors();
  const Icon = icons[name];
  return <Icon color={color ?? colors.text} size={size} strokeWidth={strokeWidth} {...rest} />;
}
