import { StyleSheet } from "react-native";

import { Radii } from "@/constants/theme";

import type { OnboardingColors } from "./onboardingTheme";

export function createOnboardingStyles(colors: OnboardingColors) {
  return StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 22,
    paddingTop: 10,
  },
  scrollContentGrow: {
    flexGrow: 1,
  },
  fixedBody: {
    flex: 1,
    paddingHorizontal: 22,
    paddingTop: 10,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: 12,
    gap: 14,
  },
  backButton: {
    width: 46,
    height: 46,
    borderRadius: Radii.pill,
    backgroundColor: colors.surfaceStrong,
    alignItems: "center",
    justifyContent: "center",
  },
  progressWrap: {
    flex: 1,
    gap: 10,
  },
  progressTrack: {
    height: 7,
    borderRadius: Radii.pill,
    backgroundColor: colors.progressTrack,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: Radii.pill,
    backgroundColor: colors.progressFill,
  },
  stageChip: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: Radii.pill,
    backgroundColor: colors.accentMuted,
  },
  footer: {
    position: "absolute",
    left: 22,
    right: 22,
    bottom: 0,
    backgroundColor: colors.bg,
    paddingTop: 14,
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: 24,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: colors.primaryText,
    fontSize: 18,
  },
  nativePrimaryButtonHost: {
    width: "100%",
    minHeight: 56,
  },
  welcome: {
    flex: 1,
    paddingHorizontal: 36,
    paddingTop: 52,
    paddingBottom: 0,
    justifyContent: "space-between",
  },
  welcomeHero: {
    alignItems: "center",
    gap: 18,
    marginTop: 96,
  },
  logoMark: {
    width: 148,
    height: 132,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  logoWordmark: {
    color: colors.text,
    fontSize: 34,
    letterSpacing: -1.1,
  },
  logoSparkLeft: {
    position: "absolute",
    left: 16,
    bottom: 18,
  },
  logoSparkRight: {
    position: "absolute",
    right: 10,
    top: 12,
  },
  welcomeBody: {
    gap: 14,
  },
  welcomeTitle: {
    color: colors.text,
    fontSize: 28,
    letterSpacing: -0.9,
  },
  welcomeText: {
    fontSize: 17,
    lineHeight: 24,
  },
  welcomeFooter: {
    gap: 18,
  },
  skipText: {
    textAlign: "center",
  },
  stepSection: {
    gap: 20,
  },
  centeredStep: {
    alignItems: "center",
  },
  stepSectionFill: {
    flex: 1,
  },
  heroPanel: {
    height: 210,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  heroPanelFill: {
    flex: 1,
    height: undefined,
    minHeight: 132,
  },
  heroSparkTop: {
    position: "absolute",
    top: 42,
    right: 42,
  },
  heroSparkBottom: {
    position: "absolute",
    bottom: 48,
    left: 30,
  },
  titleBlock: {
    gap: 10,
  },
  stepTitle: {
    color: colors.text,
    fontSize: 26,
    letterSpacing: -0.6,
  },
  stepBody: {
    fontSize: 16,
    lineHeight: 22,
  },
  centerTitle: {
    color: colors.text,
    textAlign: "center",
    fontSize: 28,
    lineHeight: 34,
    letterSpacing: 0,
  },
  largeCenterTitle: {
    color: colors.text,
    maxWidth: 320,
    textAlign: "center",
    fontSize: 28,
    lineHeight: 35,
    letterSpacing: 0,
  },
  titleIconWrap: {
    alignItems: "center",
    gap: 8,
  },
  centerSubtitle: {
    maxWidth: 330,
    textAlign: "center",
    fontSize: 15,
    lineHeight: 21,
  },
  optionList: {
    gap: 14,
  },
  optionCard: {
    minHeight: 60,
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: "transparent",
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  optionCardSelected: {
    borderColor: colors.accent,
  },
  optionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    flex: 1,
  },
  optionIcon: {
    width: 28,
    alignItems: "center",
  },
  optionCopy: {
    flex: 1,
    gap: 4,
  },
  optionLabel: {
    fontSize: 18,
  },
  optionCheck: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  optionCheckSelected: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accentSoft,
  },
  valueCard: {
    borderRadius: 24,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 20,
    paddingVertical: 20,
    gap: 10,
  },
  valueLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  valueText: {
    color: colors.accentSoft,
    fontSize: 30,
  },
  weightInputRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
  },
  weightInput: {
    color: colors.accentSoft,
    fontSize: 30,
    fontWeight: "700",
    padding: 0,
    minWidth: 110,
  },
  weightUnit: {
    color: colors.accentSoft,
    fontSize: 26,
    fontWeight: "700",
  },
  valueCardCentered: {
    alignItems: "center",
    paddingVertical: 44,
    gap: 12,
  },
  valueTextBig: {
    color: colors.accentSoft,
    fontSize: 46,
  },
  valueCaptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  inlineHint: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  measurementStack: {
    gap: 14,
  },
  measurementField: {
    gap: 8,
  },
  measurementLabelRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 12,
  },
  measurementCard: {
    minHeight: 60,
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  measurementValue: {
    color: colors.accentSoft,
    fontSize: 22,
  },
  stack: {
    gap: 14,
  },
  chipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  chip: {
    minHeight: 48,
    borderRadius: Radii.pill,
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  chipSelected: {
    borderColor: colors.accent,
    backgroundColor: "rgba(110,91,255,0.14)",
  },
  chipText: {
    color: colors.text,
  },
  notesWrap: {
    gap: 10,
  },
  inputLabel: {
    color: colors.text,
  },
  notesCard: {
    borderRadius: 24,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 12,
    minHeight: 120,
  },
  notesInput: {
    color: colors.text,
    fontSize: 16,
    lineHeight: 24,
    minHeight: 96,
    textAlignVertical: "top",
  },
  biasCard: {
    borderRadius: 28,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  biasCardDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
  },
  biasCardCopy: {
    flex: 1,
    gap: 8,
  },
  biasTitle: {
    color: colors.text,
  },
  biasExampleText: {
    lineHeight: 24,
  },
  sliderSection: {
    gap: 18,
    paddingHorizontal: 6,
    marginTop: 4,
  },
  nativeSliderHost: {
    minHeight: 44,
    justifyContent: "center",
  },
  sliderTrack: {
    height: 40,
    justifyContent: "center",
    position: "relative",
  },
  sliderBase: {
    height: 8,
    borderRadius: Radii.pill,
    backgroundColor: colors.sliderTrack,
  },
  sliderThumb: {
    position: "absolute",
    marginLeft: -18,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
  },
  sliderLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sliderLabelItem: {
    width: 58,
    alignItems: "center",
    gap: 8,
  },
  sliderLabelItemActive: {
    opacity: 1,
  },
  sliderLabelItemMuted: {
    opacity: 0.35,
  },
  sliderDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#445877",
  },
  sliderDotActive: {
    transform: [{ scale: 1.7 }],
  },
  nativeSlider: {
    width: "100%",
    height: 40,
  },
  sliderLabelText: {
    textAlign: "center",
  },
  summaryCard: {
    width: "100%",
    borderRadius: 28,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    gap: 14,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  goalTargetRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
  },
  summaryArrow: {
    flex: 1,
    alignItems: "center",
  },
  chartWrap: {
    gap: 4,
  },
  chartLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 18,
  },
  metricRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingVertical: 13,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  metricLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  metricIcon: {
    width: 26,
    alignItems: "center",
  },
  metricLabel: {
    fontSize: 17,
    lineHeight: 23,
  },
  metricValue: {
    fontSize: 20,
    letterSpacing: 0,
  },
  linkButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 6,
  },
  switchCard: {
    minHeight: 86,
    borderRadius: 24,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  switchLabelWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    flex: 1,
  },
  switchTextWrap: {
    flex: 1,
    gap: 4,
  },
  metabolismBlock: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 22,
    padding: 16,
  },
  metabolismIconBlock: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "rgba(51,169,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  metabolismStats: {
    flex: 1,
    flexDirection: "row",
    gap: 12,
  },
  metabolismStat: {
    flex: 1,
    gap: 8,
  },
  statLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  compactHeading: {
    fontSize: 18,
    letterSpacing: 0,
  },
  reasoningCard: {
    borderRadius: 28,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
    gap: 12,
  },
  reasoningTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  reasoningText: {
    fontSize: 17,
    lineHeight: 25,
  },
  sectionPill: {
    alignSelf: "center",
    borderRadius: Radii.pill,
    backgroundColor: colors.accentMuted,
    paddingHorizontal: 16,
    paddingVertical: 7,
  },
  accuracyLogos: {
    minHeight: 120,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  appTile: {
    width: 76,
    height: 76,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-5deg" }],
  },
  appTileSmall: {
    width: 66,
    height: 66,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 4,
    borderColor: "#FFFFFF",
  },
  appTileStack: {
    flexDirection: "row",
    marginLeft: 4,
  },
  appTileAmy: {
    backgroundColor: "#F4F1EC",
  },
  appTileMfp: {
    backgroundColor: "#0679E8",
    transform: [{ rotate: "3deg" }],
  },
  appTileLose: {
    backgroundColor: "#FF9500",
    marginLeft: -10,
    transform: [{ rotate: "-2deg" }],
  },
  accuracyCallout: {
    width: "100%",
    borderRadius: 28,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 18,
  },
  calloutIcon: {
    alignSelf: "center",
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(110,91,255,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  accuracyCalloutText: {
    textAlign: "center",
    fontSize: 19,
    lineHeight: 26,
    letterSpacing: 0,
  },
  calloutLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  calloutLinkText: {
    fontSize: 16,
    lineHeight: 22,
  },
  dividerTitleRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.divider,
  },
  proofTitle: {
    color: colors.text,
    textAlign: "center",
    fontSize: 21,
    letterSpacing: 0,
  },
  accuracyBanner: {
    borderRadius: 28,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  compareLogo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  compareLogoMuted: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  scoreRow: {
    width: "100%",
    flexDirection: "row",
    gap: 12,
  },
  scoreCard: {
    flex: 1,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 14,
    gap: 4,
  },
  scoreGood: {
    backgroundColor: "rgba(37, 102, 45, 0.34)",
  },
  scoreWarm: {
    backgroundColor: "rgba(93, 58, 27, 0.34)",
  },
  scoreValueRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 3,
  },
  scoreNumber: {
    fontSize: 28,
    letterSpacing: 0,
  },
  goodScore: {
    color: "#52FF91",
  },
  warmScore: {
    color: "#FFB357",
  },
  neutralScore: {
    color: "#F2DD43",
  },
  badScore: {
    color: "#FF6767",
  },
  tableCard: {
    width: "100%",
    borderRadius: 28,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  tableHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 12,
  },
  tableHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  tableRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 18,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  tableLabel: {
    flex: 1,
  },
  badge: {
    minWidth: 42,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    alignItems: "center",
  },
  badgeGood: {
    backgroundColor: "rgba(82,255,145,0.14)",
  },
  badgeNeutral: {
    backgroundColor: "rgba(242,221,67,0.14)",
  },
  badgeBad: {
    backgroundColor: "rgba(255,103,103,0.14)",
  },
  compareArrow: {
    justifyContent: "center",
  },
  compareTile: {
    flex: 1,
    borderRadius: 22,
    padding: 14,
    gap: 6,
    minHeight: 108,
    justifyContent: "center",
  },
  compareValue: {
    fontSize: 27,
    letterSpacing: 0,
  },
  compareGood: {
    backgroundColor: "rgba(30, 91, 49, 0.46)",
  },
  compareWarm: {
    backgroundColor: "rgba(86, 58, 31, 0.46)",
  },
  compareNeutral: {
    backgroundColor: colors.segmented,
  },
  detailExampleCard: {
    width: "100%",
    minHeight: 178,
    borderRadius: 28,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 16,
    paddingTop: 48,
    paddingBottom: 16,
    position: "relative",
  },
  detailSticker: {
    position: "absolute",
    top: -34,
    alignSelf: "center",
    width: 94,
    height: 86,
    borderRadius: 24,
    backgroundColor: "#F5F2EC",
    borderWidth: 4,
    borderColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-5deg" }],
  },
  detailCompareRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
  },
  methodCard: {
    width: "100%",
    minHeight: 286,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: 20,
    gap: 18,
    overflow: "hidden",
  },
  methodCardPhoto: {
    backgroundColor: "rgba(83, 39, 89, 0.48)",
  },
  methodCardMenu: {
    backgroundColor: "rgba(86, 59, 31, 0.48)",
  },
  methodVisualRow: {
    minHeight: 150,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  phoneMock: {
    width: 116,
    height: 172,
    borderRadius: 30,
    backgroundColor: "#0F0F11",
    borderWidth: 5,
    borderColor: "#303039",
    padding: 10,
    alignItems: "center",
    position: "relative",
    transform: [{ rotate: "-7deg" }],
  },
  phoneNotch: {
    width: 46,
    height: 11,
    borderRadius: 8,
    backgroundColor: "#08080A",
    position: "absolute",
    top: 8,
  },
  phoneLabel: {
    marginTop: 14,
    letterSpacing: 1.2,
  },
  phoneFood: {
    width: 86,
    height: 96,
    borderRadius: 18,
    marginTop: 10,
  },
  phoneFoodPhoto: {
    backgroundColor: "#604226",
  },
  phoneFoodMenu: {
    backgroundColor: "#E9DFCE",
  },
  phoneShutter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 3,
    borderColor: "#FFFFFF",
    marginTop: 8,
  },
  detectPanel: {
    flex: 1,
    borderRadius: 22,
    backgroundColor: "rgba(23,23,25,0.84)",
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: 16,
    gap: 6,
  },
  detectLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  detectValue: {
    fontSize: 26,
    letterSpacing: 0,
  },
  detectItem: {
    fontSize: 14,
    lineHeight: 20,
  },
  methodCopyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  methodIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  methodIconPhoto: {
    backgroundColor: "rgba(255, 98, 229, 0.22)",
  },
  methodIconMenu: {
    backgroundColor: "rgba(255, 179, 87, 0.18)",
  },
  methodCopy: {
    flex: 1,
    gap: 3,
  },
  methodTitle: {
    fontSize: 20,
    lineHeight: 25,
  },
  methodBody: {
    fontSize: 14,
    lineHeight: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: "flex-end",
    padding: 14,
  },
  nativeSheetHost: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  sheet: {
    borderRadius: 30,
    backgroundColor: colors.sheet,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 16,
  },
  sheetHandle: {
    width: 64,
    height: 5,
    borderRadius: Radii.pill,
    backgroundColor: colors.sheetHandle,
    alignSelf: "center",
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sheetScroll: {
    maxHeight: 280,
  },
  sheetItem: {
    minHeight: 52,
    borderRadius: 18,
    paddingHorizontal: 18,
    justifyContent: "center",
  },
  sheetItemActive: {
    backgroundColor: colors.segmented,
  },
  segmented: {
    flexDirection: "row",
    backgroundColor: colors.segmented,
    borderRadius: Radii.pill,
    padding: 3,
  },
  segment: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: Radii.pill,
  },
  segmentActive: {
    backgroundColor: colors.segmentActive,
  },
  pickerItem: {
    fontSize: 22,
    color: colors.text,
  },
  weightPickerRow: {
    flexDirection: "row",
  },
  weightPickerColumn: {
    flex: 1,
  },
  nativePicker: {
    width: "100%",
  },
  birthInputs: {
    flexDirection: "row",
    gap: 12,
  },
  birthField: {
    flex: 1,
    gap: 8,
  },
  birthInput: {
    minHeight: 50,
    borderRadius: 18,
    backgroundColor: colors.surfaceAlt,
    color: colors.text,
    paddingHorizontal: 14,
    fontSize: 18,
  },
  sheetButtons: {
    gap: 12,
  },
  });
}
